### ISSUE TITLE
Could the docker image be published to a repository?

### ISSUE THREAD

**Issue by jorgentol** [d-touw/SMO_Online_Docker#1]
Hello,

It'd be great if the image could be published to a repository. Dockerhub or otherwise.
In my particular situation this would allow for far easier deployment.

**Comment by d-touw** [comment]
Sure, give me a moment and I will make it happen.

**Comment by d-touw** [comment]
The images are available [here](https://hub.docker.com/repository/docker/dasteen25/smo_online_server/tags?page=1&ordering=last_updated). Make sure you have the correct tag for the architecture, I will try to make it one image for every architecture.

**Comment by d-touw** [comment]
Edit: If you give me a bit longer, I have a fix for the tags.

**Comment by d-touw** [comment]
The image is available under dasteen25/smo_online_server. No need to worry about tags anymore.
